# Generated by Django 6.1.1 on 2026-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='укажите название блога')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='загрузите фото блога')),
                ('description', models.TextField(blank=True, verbose_name='укажите описание блога')),
                ('author_email', models.EmailField(default='_@gmail.com', max_length=254, verbose_name='укажите свою почту')),
                ('categories', models.CharField(choices=[('Детектив', 'Детектив'), ('Фантастика', 'Фантастика'), ('Комедия', 'Комедия')], default='Комедия', verbose_name='выберите категорию блога')),
                ('url_blog', models.URLField(blank=True, verbose_name='Есть ссылка на youtube?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'список блогов',
            },
        ),
    ]
