# Generated by Django 6.1.1 on 2026-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(choices=[('Детектив', 'Детектив'), ('Фантастика', 'Фантастика'), ('Комедия', 'Комедия')], default='Комедия', max_length=100, verbose_name='выберите категорию блога'),
        ),
    ]
