# Generated by Django 6.1.1 on 2026-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BMW', max_length=100)),
                ('person', models.CharField(default='Иванов Иван', max_length=100)),
            ],
        ),
    ]
