# Generated by Django 6.1.1 on 2026-10-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateNumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_car', models.CharField(default='0_KG______', max_length=100)),
                ('car_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
