# Generated by Django 6.1.1 on 2026-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=models.ManyToManyField(null=True, to='cars.categorycar'),
        ),
    ]
